# Generated by Django 4.0.4 on 2023-01-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='name',
            new_name='league_name',
        ),
    ]
