# Generated by Django 4.0.4 on 2023-02-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeper_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeperuser',
            name='password',
        ),
        migrations.AddField(
            model_name='sleeperuser',
            name='avatar',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='sleeperuser',
            name='display_name',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='sleeperuser',
            name='user_id',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='sleeperuser',
            name='username',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
