# Generated by Django 4.0.4 on 2023-01-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_platforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='api_url',
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('Sleeper', 'Sleeper'), ('Yahoo', 'Yahoo')], default='Sleeper', max_length=100),
        ),
    ]
