# Generated by Django 4.0.4 on 2023-02-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_delete_league'),
        ('fantasy_platforms', '0002_remove_platform_api_url_alter_platform_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
